// SPDX-License-Identifier: AGPL-3.0-or-later

package decision

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
)

const SemanticPolicyContextVersion uint16 = 1

// SemanticPolicyClause is reviewed policy input for an optional semantic
// evaluator. It may only describe a narrowing result. The evaluator still
// runs below deterministic policy and cannot grant authority.
type SemanticPolicyClause struct {
	ID                   string                `json:"id"`
	StatementID          string                `json:"statement_id"`
	StatementRevision    uint64                `json:"statement_revision"`
	Instruction          string                `json:"instruction"`
	Actions              []string              `json:"actions"`
	OutcomeOnMatch       Outcome               `json:"outcome_on_match"`
	ApprovalPlanID       string                `json:"approval_plan_id,omitempty"`
	ApprovalPlanRevision uint64                `json:"approval_plan_revision,omitempty"`
	MetadataFields       []string              `json:"metadata_fields"`
	FailureMode          EvaluationFailureMode `json:"failure_mode"`
	ExpiresAt            int64                 `json:"expires_at,omitempty"`
}

// SemanticPolicyContext is generated by the authority from active reviewed
// statements. Workload callers cannot supply or replace it on the primary
// authorization endpoint.
type SemanticPolicyContext struct {
	Version     uint16                 `json:"version"`
	TenantID    string                 `json:"tenant_id"`
	Clauses     []SemanticPolicyClause `json:"clauses"`
	ContextHash string                 `json:"context_hash"`
}

type SemanticPolicyContextProvider interface {
	SemanticPolicyContext(context.Context, Intent) (SemanticPolicyContext, bool, error)
}

type SemanticContextAuthorizer interface {
	AuthorizeSemantic(context.Context, Intent, SemanticPolicyContext) (Decision, error)
}

type SemanticContextDisclosureAuthorizer interface {
	AuthorizeSemanticDisclosure(context.Context, Intent, DisclosureBinding, SemanticPolicyContext) (Decision, error)
}

// SemanticContextFederatedContentAuthorizer is the Pilot-hosted semantic
// extension. Workload callers cannot submit SemanticPolicyContext on the
// public authorization route; the authority supplies reviewed active clauses.
type SemanticContextFederatedContentAuthorizer interface {
	AuthorizeSemanticFederatedContent(context.Context, Intent, FederatedContent, SemanticPolicyContext) (Decision, error)
}

func NewSemanticPolicyContext(tenantID string, clauses []SemanticPolicyClause) (SemanticPolicyContext, error) {
	context := SemanticPolicyContext{Version: SemanticPolicyContextVersion, TenantID: strings.TrimSpace(tenantID), Clauses: cloneSemanticClauses(clauses)}
	hash, err := context.Hash()
	if err != nil {
		return SemanticPolicyContext{}, err
	}
	context.ContextHash = hash
	if err := context.Validate(); err != nil {
		return SemanticPolicyContext{}, err
	}
	return context, nil
}

func (policy SemanticPolicyContext) Validate() error {
	if policy.Version != SemanticPolicyContextVersion || validateIdentifier("semantic tenant_id", policy.TenantID) != nil || len(policy.Clauses) == 0 || len(policy.Clauses) > 64 || !lowerHex(policy.ContextHash, 64) {
		return fmt.Errorf("decision: invalid semantic policy context")
	}
	seen := make(map[string]struct{}, len(policy.Clauses))
	for _, clause := range policy.Clauses {
		if err := clause.Validate(); err != nil {
			return err
		}
		if _, duplicate := seen[clause.ID]; duplicate {
			return fmt.Errorf("decision: duplicate semantic clause %q", clause.ID)
		}
		seen[clause.ID] = struct{}{}
	}
	hash, err := policy.Hash()
	if err != nil || hash != policy.ContextHash {
		return fmt.Errorf("decision: semantic policy context hash mismatch")
	}
	return nil
}

func (policy SemanticPolicyContext) ValidateIntent(intent Intent, now int64) error {
	if err := policy.Validate(); err != nil {
		return err
	}
	if policy.TenantID != intent.TenantID {
		return fmt.Errorf("decision: semantic policy tenant mismatch")
	}
	matched := false
	for _, clause := range policy.Clauses {
		if clause.ExpiresAt > 0 && clause.ExpiresAt <= now {
			return fmt.Errorf("decision: semantic policy clause is expired")
		}
		for _, action := range clause.Actions {
			if action == intent.Action {
				matched = true
				break
			}
		}
	}
	if !matched {
		return fmt.Errorf("decision: semantic policy has no clause for action %q", intent.Action)
	}
	return nil
}

func (policy SemanticPolicyContext) Hash() (string, error) {
	copy := policy
	copy.ContextHash = ""
	payload, err := json.Marshal(copy)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(payload)
	return hex.EncodeToString(sum[:]), nil
}

func (clause SemanticPolicyClause) Validate() error {
	for name, value := range map[string]string{"semantic clause id": clause.ID, "semantic statement id": clause.StatementID} {
		if err := validateIdentifier(name, value); err != nil {
			return err
		}
	}
	if clause.StatementRevision == 0 || strings.TrimSpace(clause.Instruction) == "" || len(clause.Instruction) > 2048 || strings.ContainsRune(clause.Instruction, 0) || len(clause.Actions) == 0 || len(clause.Actions) > 64 {
		return fmt.Errorf("decision: invalid semantic clause content")
	}
	actions := make(map[string]struct{}, len(clause.Actions))
	for _, action := range clause.Actions {
		if !validAction(action) {
			return fmt.Errorf("decision: invalid semantic clause action %q", action)
		}
		if _, duplicate := actions[action]; duplicate {
			return fmt.Errorf("decision: duplicate semantic clause action")
		}
		actions[action] = struct{}{}
	}
	if clause.OutcomeOnMatch != Deny && clause.OutcomeOnMatch != ApprovalRequired {
		return fmt.Errorf("decision: semantic clause may only deny or require approval")
	}
	if clause.OutcomeOnMatch == ApprovalRequired {
		if err := validateIdentifier("semantic approval plan", clause.ApprovalPlanID); err != nil || clause.ApprovalPlanRevision == 0 {
			if err != nil {
				return err
			}
			return fmt.Errorf("decision: semantic approval clause requires a plan revision")
		}
	} else if clause.ApprovalPlanID != "" || clause.ApprovalPlanRevision != 0 {
		return fmt.Errorf("decision: semantic deny clause cannot name approval plan")
	}
	if clause.FailureMode != EvaluationFailureOpen && clause.FailureMode != EvaluationFailureClosed {
		return fmt.Errorf("decision: semantic clause requires explicit failure mode")
	}
	if clause.ExpiresAt < 0 || len(clause.MetadataFields) == 0 || len(clause.MetadataFields) > 16 {
		return fmt.Errorf("decision: invalid semantic clause metadata")
	}
	fields := make(map[string]struct{}, len(clause.MetadataFields))
	for _, field := range clause.MetadataFields {
		if err := validateIdentifier("semantic metadata field", field); err != nil {
			return err
		}
		if _, duplicate := fields[field]; duplicate {
			return fmt.Errorf("decision: duplicate semantic metadata field")
		}
		fields[field] = struct{}{}
	}
	return nil
}

func cloneSemanticClauses(clauses []SemanticPolicyClause) []SemanticPolicyClause {
	result := make([]SemanticPolicyClause, len(clauses))
	copy(result, clauses)
	for index := range result {
		result[index].Actions = append([]string(nil), result[index].Actions...)
		result[index].MetadataFields = append([]string(nil), result[index].MetadataFields...)
	}
	return result
}
